### ISSUE TITLE
undefined symbol: __libc_dlopen_mode, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by secure-77** [apitrace/apitrace#910]
Hi,

Im getting this error and have no clue how to fix it:

````
apitrace: loaded into /home/user/apitrace-latest-Linux/bin/myapp
./myapp: symbol lookup error: /home/user/apitrace-latest-Linux/bin/../lib/apitrace/wrappers/glxtrace.so: undefined symbol: __libc_dlopen_mode, version GLIBC_PRIVATE
````

**Comment by jrfonseca** [comment]
This looks like https://github.com/apitrace/apitrace/issues/756 which was fixed long ago.

Confirm you have a recent checkout/build of apitrace.

**Comment by secure-77** [comment]
I got the binary from the homepage

```bash
./apitrace version 
apitrace git-d84eae9a https://github.com/apitrace/apitrace/actions/runs/7915894676
```

**Comment by jrfonseca** [comment]
I see...   Those Linux binaries were built on a old Ubuntu version (the idea being this way it would work on both old and newer version) but in fact this causes problems because the old Ubuntu version has  `__libc_dlopen_mode` symbol, whereas new don't!

I suppose the right thing to do is to unconditionally never use `__libc_dlopen_mode`...

**Comment by jrfonseca** [comment]
New binaries that don't suffer from this issue should appear in a few hours.

**Comment by secure-77** [comment]
Thank you very much!

Binaries still not updated on the homepage but I was able to build it and its working fine 👍
